# Generated by Django 6.0.1 on 2026-01-08 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('documento', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='DNI Alumno')),
                ('apellido', models.CharField(max_length=100)),
                ('nombres', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1)),
                ('nivel', models.CharField(blank=True, max_length=10, verbose_name='Nivel (I5/P/S)')),
                ('curso', models.CharField(blank=True, max_length=10)),
                ('division', models.CharField(blank=True, max_length=10)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('telefono1', models.CharField(blank=True, max_length=50)),
                ('telefono2', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('barrio', models.CharField(blank=True, max_length=100)),
                ('padre_nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre del Padre')),
                ('padre_dni', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='DNI Padre')),
                ('padre_direccion', models.CharField(blank=True, max_length=200)),
                ('padre_telefono1', models.CharField(blank=True, max_length=50)),
                ('padre_telefono2', models.CharField(blank=True, max_length=50)),
                ('padre_email', models.EmailField(blank=True, max_length=254)),
                ('madre_nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre de la Madre')),
                ('madre_dni', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='DNI Madre')),
                ('madre_direccion', models.CharField(blank=True, max_length=200)),
                ('madre_telefono1', models.CharField(blank=True, max_length=50)),
                ('madre_telefono2', models.CharField(blank=True, max_length=50)),
                ('madre_email', models.EmailField(blank=True, max_length=254)),
                ('tutor_nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre del Tutor')),
                ('tutor_dni', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='DNI Tutor')),
                ('tutor_direccion', models.CharField(blank=True, max_length=200)),
                ('tutor_telefono1', models.CharField(blank=True, max_length=50)),
                ('tutor_telefono2', models.CharField(blank=True, max_length=50)),
                ('tutor_email', models.EmailField(blank=True, max_length=254)),
                ('familia', models.IntegerField(default=0, help_text='ID de grupo familiar')),
                ('recargo', models.BooleanField(default=False)),
                ('saldo_moroso', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Total Adeudado')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellido', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('orden', models.IntegerField(default=0, help_text='Orden para mostrar en la vista')),
            ],
            options={
                'verbose_name': 'Concepto de Deuda',
                'verbose_name_plural': 'Conceptos de Deuda',
                'ordering': ['orden', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('parcial', 'Pago Parcial')], default='pendiente', max_length=20)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deudas', to='portal.alumno')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='portal.conceptodeuda')),
            ],
            options={
                'verbose_name': 'Registro de Deuda',
                'verbose_name_plural': 'Registros de Deuda',
                'ordering': ['concepto__orden', 'concepto__codigo'],
            },
        ),
    ]
