# Generated by Django 6.0.1 on 2026-01-09 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_transferencia', models.CharField(default='colegio.nuevosiglo', max_length=100)),
                ('cbu', models.CharField(default='0000000000000000000000', max_length=22)),
                ('password_default', models.CharField(default='Colegio123', max_length=50)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuración del Sistema',
            },
        ),
        migrations.AddField(
            model_name='registrodeuda',
            name='periodo',
            field=models.CharField(blank=True, help_text='Ej: 2024-03', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrodeuda',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('comprobante_enviado', 'Comprobante Enviado'), ('pago_verificado', 'Pago Verificado'), ('pagado', 'Pagado'), ('parcial', 'Pago Parcial')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operacion', models.CharField(editable=False, max_length=50, unique=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Verificación'), ('verificado', 'Pago Verificado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='portal.registrodeuda')),
                ('usuario_responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_enviados', to=settings.AUTH_USER_MODEL)),
                ('usuario_verificador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_verificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='DNI')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('padre', 'Padre/Responsable')], default='padre', max_length=20)),
                ('must_change_password', models.BooleanField(default=True, verbose_name='Debe cambiar contraseña')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('PASSWORD_CHANGED', 'Cambio de Contraseña'), ('PAYMENT_SUBMITTED', 'Pago Enviado'), ('PAYMENT_VERIFIED', 'Pago Verificado'), ('IMPORT', 'Importación de Datos'), ('EXPORT', 'Exportación de Datos'), ('CONFIG_UPDATE', 'Actualización de Configuración'), ('USER_CREATED', 'Usuario Creado'), ('PASSWORD_RESET', 'Contraseña Reseteada')], max_length=50)),
                ('detalles', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
