# Generated by Django 6.0.1 on 2026-02-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_configuracionsistema_registrodeuda_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodeuda',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('comprobante_enviado', 'Comprobante Enviado'), ('pago_verificado', 'Pago Verificado'), ('pagado', 'Pagado'), ('parcial', 'Pago Parcial'), ('no_corresponde', 'No Corresponde')], default='pendiente', max_length=20),
        ),
    ]
