# Generated by Django 6.0.2 on 2026-03-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_registrodeuda_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='accion',
            field=models.CharField(choices=[('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('PASSWORD_CHANGED', 'Cambio de Contraseña'), ('PAYMENT_SUBMITTED', 'Pago Enviado'), ('PAYMENT_VERIFIED', 'Pago Verificado'), ('IMPORT', 'Importación de Datos'), ('EXPORT', 'Exportación de Datos'), ('CONFIG_UPDATE', 'Actualización de Configuración'), ('USER_CREATED', 'Usuario Creado'), ('PASSWORD_RESET', 'Contraseña Reseteada'), ('EMAIL_SENT', 'Email Enviado')], max_length=50),
        ),
    ]
